[build]
  base = "backend"
  command = "npm run build"
  publish = ".next"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/strapi/:splat"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/.netlify/functions/strapi/admin/:splat"
  status = 200
